---
language: bash
services: docker

env:
  - IMAGE=ubuntu VERSION=xenial VARIANT=
  - IMAGE=debian VERSION=stretch VARIANT=
  - IMAGE=php VERSION= VARIANT=
  - IMAGE=php VERSION=7.2 VARIANT=
  - IMAGE=node VERSION= VARIANT=
  - IMAGE=node VERSION=6.10 VARIANT=
  - IMAGE=node VERSION=7.6 VARIANT=
  - IMAGE=node VERSION=7.7 VARIANT=
  - IMAGE=ansible VERSION= VARIANT=
  - IMAGE=ansible VERSION=2.5 VARIANT=
  - IMAGE=ansible VERSION=2.6 VARIANT=
  - IMAGE=ansible VERSION=2.7 VARIANT=
  - IMAGE=mpc VERSION= VARIANT=

script:
  - if [ "${TRAVIS_EVENT_TYPE:-cron}" != "cron" ] ; then docker pull "dealerdirect/$IMAGE:${VERSION:-latest}${VARIANT:+-$VARIANT}" || /bin/true ; fi
  - travis_retry docker build --cache-from "dealerdirect/$IMAGE:${VERSION:-latest}${VARIANT:+-$VARIANT}" -t "dealerdirect/$IMAGE:${VERSION:-latest}${VARIANT:+-$VARIANT}" -f "images/$IMAGE${VERSION:+/$VERSION}${VARIANT:+/$VARIANT}/Dockerfile" .

after_script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "dealerdirect/$IMAGE:${VERSION:-latest}${VARIANT:+-$VARIANT}";
    fi
