---
language: bash
services: docker

env:
  - IMAGE=debian VERSION=jessie VARIANT=
  - IMAGE=php VERSION= VARIANT=
  - IMAGE=php VERSION=5.4 VARIANT=
  - IMAGE=php VERSION=5.6 VARIANT=
  - IMAGE=php VERSION=7.0 VARIANT=
  - IMAGE=php VERSION=7.1 VARIANT=
  - IMAGE=node VERSION= VARIANT=
  - IMAGE=node VERSION=4.8 VARIANT=
  - IMAGE=node VERSION=6.10 VARIANT=
  - IMAGE=node VERSION=7.6 VARIANT=
  - IMAGE=node VERSION=7.7 VARIANT=
  - IMAGE=ansible VERSION= VARIANT=
  - IMAGE=ansible VERSION=1.9 VARIANT=
  - IMAGE=ansible VERSION=2.0 VARIANT=
  - IMAGE=ansible VERSION=2.1 VARIANT=
  - IMAGE=ansible VERSION=2.2 VARIANT=
  - IMAGE=mpc VERSION= VARIANT=

script:
  - travis_retry docker build -t "dealerdirect/$IMAGE:${VERSION:-latest}${VARIANT:+-$VARIANT}" -f "images/$IMAGE${VERSION:+/$VERSION}${VARIANT:+/$VARIANT}/Dockerfile" .

after_script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "dealerdirect/$IMAGE:${VERSION:-latest}${VARIANT:+-$VARIANT}";
    fi
